//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaning1.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int StatusId { get; set; }
        public int DetergentId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual Detergent Detergent { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
